version: '3'
services:
  api:
    container_name: 'api-app'
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - DEV_ARTJOB_DB=dev_artjob
      - DEV_ARTJOB_PASS=postgrespw
      - DEV_ARTJOB_HOST=db
      - DEV_ARTJOB_USER=postgres
    build: .
    image: artjob-api
  db:
    container_name: 'api-db'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - C:/Users/retan/docker-volumes/artjob/postgres:/var/lib/postgresql/data
    image: postgres
